apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/ems_ops?useSSL=false&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: ems_ops
  # SPRING_DATASOURCE_PASSWORD: ems-ops
