apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: db-secret
spec:
    provider: aws
    secretObjects:
       - secretName: mysql-secret
         type: Opaque
         data:
           - objectName: /test/SPRING_DATASOURCE_PASSWORD
             key: password
    parameters:
        objects: |
            - objectName: "/test/SPRING_DATASOURCE_PASSWORD"
              objectType: "ssmparameter"